### ISSUE TITLE
only the segment top color line display in the left edge

### ISSUE THREAD

**Issue by zeffon** [wix/react-native-custom-segmented-control#1]
Hi,
Thanks for this awesome control.
I install  react-native-custom-segmented-control in your guide, but when  i run the simulator  only the segment top color line display in the left edge.
below is my project dependencies
 "dependencies": {
    "babel-preset-react-native-stage-0": "*",
    "react": "^15.3.1",
    "react-native": "^0.33.0",
    "react-native-carousel": "^0.10.0",
    "react-native-multi-slider": "^0.3.5",
    "react-native-navigation": "file:../",
    "react-native-picker": "^3.0.5",
    "react-native-slider": "^0.9.1",
    "react-native-swiper": "^1.4.11",
    "react-redux": "^4.0.6",
    "redux": "^3.0.5",
    "redux-logger": "^2.6.1",
    "redux-thunk": "^1.0.3",
    "rn-bootstrap-buttons": "^1.0.4",
    "seamless-immutable": "^5.0.1"
  }

**Comment by gran33** [comment]
Hi @zeffon, Can u please add a screenshot?

Thanks in advance

**Comment by gran33** [comment]
@zeffon ?
