### ISSUE TITLE
No podspec file was found when upgrade RN 0.62.2 from 0.56.0

### ISSUE THREAD

**Issue by vijay-dadhich09** [wix/react-native-custom-segmented-control#13]
Hi, I upgrade RN version from '0.56.0' to '0.62.2' but I am getting the following error when installing pod. Any solution

```
[!] use_native_modules! skipped the react-native dependency 'react-native-custom-segmented-control'. No podspec file was found.
    - Check to see if there is an updated version that contains the necessary podspec file
    - Contact the library maintainers or send them a PR to add a podspec. The react-native-webview podspec is a
    good example of a package.json driven podspec. See
    https://github.com/react-native-community/react-native-webview/blob/master/react-native-webview.podspec
    - If necessary, you can disable autolinking for the dependency and link it manually. See
    https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-disable-autolinking-for-unsupported-library
```

and after this getting following error in xcode

/react-native/React/Views/RCTViewManager.h:10:9: 'React/RCTBridgeModule.h' file not found

<img width="1157" alt="Screenshot 2020-06-21 at 12 44 35" src="https://user-images.githubusercontent.com/20353762/85223748-00183a00-b3bd-11ea-8ca2-258b2abb9cfd.png">

**Comment by vijay-dadhich09** [comment]
Hi, @gran33 Do you have any solution for this problem?

**Comment by gran33** [comment]
Hey @vijay-dadhich09, this repo isn't maintained anymore.
My solution is to switch its behaviour to JS, solutions like this:
https://github.com/kirankalyan5/react-native-segmented-control-tab
