### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by beaurushton** [wix/react-native-custom-segmented-control#2]
Does this component work on android as well?  If not is it on the roadmap?

**Comment by gran33** [comment]
Hi @beaurushton, this component doesn't support `Android`.
In `Android` u have this `component` in the framework:
https://facebook.github.io/react-native/docs/viewpagerandroid.html

It will force u to have different views for each platform (`iOS` and `Android`) in different files:
`myComponent.ios.js`
`myComponent.android.js`
