### ISSUE TITLE
Invariant Violation: Native component for "CustomSegmentedControl" does not exist

### ISSUE THREAD

**Issue by ReggaePanda** [wix/react-native-custom-segmented-control#7]
Cant run this on iOS with new react-native version and react-native-navigation

<img width="531" alt="bildschirmfoto 2018-01-24 um 14 47 26" src="https://user-images.githubusercontent.com/2183135/35335356-a9f79fa0-0115-11e8-9aed-ff7fee51e893.png">

<img width="854" alt="bildschirmfoto 2018-01-24 um 14 49 09" src="https://user-images.githubusercontent.com/2183135/35335402-c5e354c0-0115-11e8-8136-dbc0452cc1cf.png">
<img width="266" alt="bildschirmfoto 2018-01-24 um 14 49 15" src="https://user-images.githubusercontent.com/2183135/35335405-c974f350-0115-11e8-8a9c-e7912c7bac36.png">

```
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 9.4.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0
```

```
    "react-native-custom-segmented-control": "^3.0.8",
    "react-native-navigation": "^1.1.352",
```

**Comment by gran33** [comment]
Hi,
Are you sure you re-run the project from xcode or hit `react-native run-ios`? The native need to be compile and build, cmd+r isn't enough.

**Comment by ReggaePanda** [comment]
yes I did. but now I use [SegmentedControlIOS](https://facebook.github.io/react-native/docs/segmentedcontrolios.html)
